# Generated by Django 4.2.7 on 2026-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_published'], name='courses_instruc_5e58ee_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_published'], name='courses_categor_9b36bb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='enrollments_student_9c8d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='enrollments_is_acti_8c11e0_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lessons_course__eb1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='progress_enrollm_c628bb_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['lesson', 'is_completed'], name='progress_lesson__a413da_idx'),
        ),
    ]
